const url = "https://kaydies.nl/sounds/",
dir = ["Samples/","WAV/"],
ext = ".mp4",
hitSounds = [
    // `clap-808`,
    // `clap-analog`,
    // `clap-crushed`,
    `clap-fat`,
    // `clap-slapper`,
    // `clap-tape`,
    // `cowbell-808`,
    // `crash-808`,
    // `crash-acoustic`,
    // `crash-noise`,
    // `crash-tape`,
    // `hihat-808`,
    // `hihat-acoustic01`,
    // `hihat-acoustic02`,
    // `hihat-analog`,
    // `hihat-digital`,
    // `hihat-dist01`,
    // `hihat-dist02`,
    // `hihat-electro`,
    // `hihat-plain`,
    // `hihat-reso`,
    `hihat-ring`,
    // `kick-808`,
    // `kick-acoustic01`,
    // `kick-acoustic02`,
    // `kick-big`,
    // `kick-classic`,
    // `kick-cultivator`,
    // `kick-deep`,
    // `kick-dry`,
    // `kick-electro01`,
    // `kick-electro02`,
    // `kick-floppy`,
    // `kick-gritty`,
    // `kick-heavy`,
    // `kick-newwave`,
    // `kick-oldschool`,
    // `kick-plain`,
    // `kick-slapback`,
    `kick-softy`,
    // `kick-stomp`,
    // `kick-tape`,
    // `kick-thump`,
    // `kick-tight`,
    // `kick-tron`,
    // `kick-vinyl01`,
    // `kick-vinyl02`,
    // `kick-zapper`,
    // `openhat-808`,
    // `openhat-acoustic01`,
    // `openhat-analog`,
    // `openhat-slick`,
    // `openhat-tight`,
    // `perc-808`,
    // `perc-chirpy`,
    `perc-hollow`,
    // `perc-laser`,
    // `perc-metal`,
    // `perc-nasty`,
    // `perc-short`,
    // `perc-tambo`,
    // `perc-tribal`,
    // `perc-weirdo`,
    // `ride-acoustic01`,
    // `ride-acoustic02`,
    // `shaker-analog`,
    // `shaker-shuffle`,
    // `shaker-suckup`,
    // `snare-808`,
    // `snare-acoustic01`,
    // `snare-acoustic02`,
    // `snare-analog`,
    // `snare-big`,
    // `snare-block`,
    // `snare-brute`,
    // `snare-dist01`,
    // `snare-dist02`,
    // `snare-dist03`,
    // `snare-electro`,
    // `snare-lofi01`,
    // `snare-lofi02`,
    // `snare-modular`,
    // `snare-noise`,
    // `snare-pinch`,
    // `snare-punch`,
    // `snare-smasher`,
    // `snare-sumo`,
    // `snare-tape`,
    // `snare-vinyl01`,
    // `snare-vinyl02`,
    // `tom-808`,
    // `tom-acoustic01`,
    // `tom-acoustic02`,
    // `tom-analog`,
    // `tom-chiptune`,
    // `tom-fm`,
    // `tom-lofi`,
    // `tom-rototom`,
    `tom-short`,
],
scapeSounds = [
    // `Braam - Braamamma`,
    // `Braam - Distorted Warps`,
    // `Braam - Intensive Stare`,
    // `Braam - Melting Pot`,
    // `Braam - Retro Pulse`,
    // `Braam - Show Title`,
    // `Braam - Sneaky Cello`,
    `Braam - Zone End`,
    // `Downer - Flying Menace`,
    // `Downer - To The Chopper`,
    // `Drone - Alien VHS`,
    // `Drone - Axe On Fire`,
    // `Drone - Crystal Cave`,
    // `Drone - Distant Orchestra`,
    // `Drone - Foreign Signal`,
    // `Drone - Holy Megalony`,
    // `Drone - Magic Pill`,
    // `Drone - Ocean Cave`,
    // `Impact - Cease Fire`,
    // `Impact - Cher Effect`,
    // `Impact - Deep Down`,
    // `Impact - Dubby Slam`,
    // `Impact - Jaw Breaker`,
    // `Impact - Lightweight`,
    `Impact - Low Blow`,
    // `Impact - Million Merits`,
    // `Impact - Nuclear Winter`,
    // `Impact - Robot Punch`,
    // `Impact - Stormy One`,
    // `Impact - Super Fast`,
    // `Impact - Thunder Dome`,
    // `Impact - Wait For It`,
    // `Metal - Big Bell`,
    // `Metal - Jump Scare`,
    // `Metal - King Gong`,
    // `Metal - Kung Boo`,
    // `Metal - Spooky Midnight`,
    // `Noise - Crash Machine`,
    // `Noise - Massive Passive`,
    // `Noise - Swirly Spinner`,
    // `Noise - Windy Cave`,
    // `Punch - Pop`,
    // `Punch - Splok`,
    // `Punch - Sploop`,
    // `Punch - Whack A Bot`,
    // `Retro - Chip Power`,
    // `Retro - Digital Eagle`,
    // `Retro - Magic Respawn`,
    // `Retro - Now You See It`,
    // `Retro - Rezo Sweep`,
    // `Retro - Shuriken Laser`,
    // `Retro - Slow Down Bro`,
    // `Retro - Swirly Reso`,
    // `Retro - Teleport Time`,
    // `Riser - Abort Takeoff`,
    // `Riser - Gathering Mana`,
    // `Riser - Noisy UFO`,
    // `Riser - Stormy Swarmy`,
    // `Short - Bass Boy`,
    // `Short - Digital Crystal`,
    // `Short - Digital Malfunction`,
    `Short - Mini Popup`,
    `Short - Ploppy Plop`,
    // `Short - Pneumatic Woodpecker`,
    `Short - Sad Little Sonar`,
    // `Short - Springy Gun`,
    // `Short - Stutter 303`,
    // `Short - Swish`,
    // `Short - Tape Confusion`,
    // `Short - Uber Vacuum`,
    // `Sub - Distant Stargate`,
    // `Sub - Mini Impact`,
    // `Sub - Sub Bees`,
    // `Sub - Subtle Meanie`,
    // `Swish - Call And Response`,
    // `Swish - Flicker Shoosh`,
    // `Swish - Gulpy Noise`,
    // `Swish - Nano Chopper`,
    // `Swish - Nice And Clean`,
    // `Swish - Noise And Creme`,
    // `Swish - Pocket Waves`,
    // `Swish - Roraring Skies`,
    `Swish - Shortnoise`,
    // `Texture - Brain Worms`,
    // `Texture - Dark Side Of The Quark`,
    `Texture - Goblet Of Wisdom`,
    // `Texture - Is There Anybody Out There`,
    // `Texture - See The Light`,
    // `Texture - What Damage`,
    // `Whoosh - Land Speeder`,
    // `Whoosh - Mini Jet`,
    // `Whoosh - Nasty Transit`,
    // `Whoosh - Rusty UFO`,
    // `Whoosh - Trapped Firecracker`,
    // `Whoosh - Triple Threat`,
]
function cacheAudio(src){
    let el = document.createElement("audio")
    el.preload = "auto"
    el.src = src
    document.body.appendChild(el)
    return el
}

function playAudio(el, volume=0.2) {
    el = new Audio(el.getAttribute("src"))
    el.currentTime = 0;
    el.volume = volume
    el.play()
}
//   const Sound = (() => {
//     var df = document.createDocumentFragment();
//     return (src) => {
//       let snd = new Audio(src);
//       df.appendChild(snd); // keep in fragment until finished playing
//       snd.play()
//       const playEnded = (e) => {}
//       snd.addEventListener("ended", playEnded);
//       return snd;
//     };
//   })();

    const bump = cacheAudio(`${[url,dir[0],`perc-hollow`,ext].join("")}`,1);
    const step = cacheAudio(`${[url,dir[0],`kick-softy`,ext].join("")}`,.5);
    const hover = cacheAudio(`${[url,dir[0],`tom-short`,ext].join("")}`,1);
    const hit = cacheAudio(`${[url,dir[1],`Short - Ploppy Plop`,ext].join("")}`,1)
    const gameStartAudio = cacheAudio(`${[url,dir[1],`Swish - Shortnoise`,ext].join("")}`,1)
    const stepStart = cacheAudio(`${[url,dir[1],`Short - Sad Little Sonar`,ext].join("")}`,0.2)

    stepStart.volume = 1
    step.volume = 0.5

export { bump, hit, gameStartAudio, hover, step, playAudio, stepStart }